DROP TABLE IF EXISTS tweet;
CREATE TABLE tweet (id INTEGER PRIMARY KEY AUTO_INCREMENT, person_id INTEGER, text VARCHAR(140), FOREIGN KEY (person_id) REFERENCES person(id));

DROP TABLE IF EXISTS person;
CREATE TABLE person (id INTEGER PRIMARY KEY AUTO_INCREMENT, name VARCHAR(200));

DROP TABLE IF EXISTS personfollower;
CREATE TABLE personfollower (follower INTEGER NOT NULL, following INTEGER NOT NULL, FOREIGN KEY (follower) REFERENCES person(id), FOREIGN KEY (following) REFERENCES person(id));